name: The Willows in the Hollow
favicon: null
layout_spectrum: 0.8048961565364152
typography_spectrum: 0.46382
title: Welcome
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02090f'
    - '#86b1be'
    - '#d4d3d8'
    - '#143581'
    - '#636268'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 1
purpose: []
