name: The Willows in the Hollow
favicon: null
layout_spectrum: 0.8048961565364152
typography_spectrum: 0.8394970656372607
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#a3b8ed'
    - '#fbfbfb'
    - '#3e5600'
    - '#7e8923'
  brandStrength: 0.27631184877827764
  lightness: 0.4375
  saturation: 0.28077921993099153
  rhythmicContrast: 0.6868917795363814
purpose: []
